version: "3"
services:
  node:
    container_name: "node"
    build:
      # velog directory를 root로 사용
      context: .
      # ./velog/Dockerfile을 사용해서 build
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
